/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FacetPack {
  constructor()
  parse(filename: string, sourceText: string, options?: ParseOptions | undefined | null): ParseResult
  transform(filename: string, sourceText: string, options?: TransformOptions | undefined | null): TransformResult
  resolve(directory: string, specifier: string, options?: ResolverOptions | undefined | null): ResolveResult
}

export declare function analyzeBatchSync(modules: Array<ModuleInput>): Array<ModuleAnalysis>

export declare function analyzeSync(filename: string, sourceText: string): ModuleAnalysis

export interface Diagnostic {
  severity: DiagnosticSeverity
  code?: string
  message: string
  filename: string
  line: number
  column: number
  endLine?: number
  endColumn?: number
  snippet?: string
  label?: string
  help?: string
  suggestion?: string
  formatted: string
}

export declare const enum DiagnosticSeverity {
  Error = 'Error',
  Warning = 'Warning',
  Info = 'Info',
  Hint = 'Hint'
}

export interface ExportInfo {
  name: string
  isDefault: boolean
  isReexport: boolean
  source?: string
}

export interface ImportInfo {
  source: string
  specifiers: Array<string>
  isSideEffect: boolean
}

export declare const enum JsxRuntime {
  Automatic = 'Automatic',
  Classic = 'Classic'
}

export interface MinifyOptions {
  compress?: boolean
  mangle?: boolean
  keepFnames?: boolean
  dropConsole?: boolean
  dropDebugger?: boolean
  sourcemap?: boolean
}

export interface MinifyResult {
  code: string
  map?: string
}

export declare function minifySync(code: string, filename: string, options?: MinifyOptions | undefined | null): MinifyResult

export interface ModuleAnalysis {
  exports: Array<ExportInfo>
  imports: Array<ImportInfo>
  hasSideEffects: boolean
}

export interface ModuleInput {
  path: string
  code: string
}

export interface ParseOptions {
  sourceType?: SourceType
  preserveParens?: boolean
}

export interface ParseResult {
  program: string
  errors: Array<string>
  diagnostics: Array<Diagnostic>
  panicked: boolean
}

export declare function parseSync(filename: string, sourceText: string, options?: ParseOptions | undefined | null): ParseResult

export declare function resolveBatchSync(directory: string, specifiers: Array<string>, options?: ResolverOptions | undefined | null): Array<ResolveResult>

export interface ResolveResult {
  path?: string
  error?: string
}

export interface ResolverOptions {
  extensions?: Array<string>
  mainFields?: Array<string>
  conditionNames?: Array<string>
}

export declare function resolveSync(directory: string, specifier: string, options?: ResolverOptions | undefined | null): ResolveResult

export interface ShakeResult {
  code: string
  map?: string
  removedExports: Array<string>
}

export declare function shakeSync(filename: string, sourceText: string, usedExports: Array<string>): ShakeResult

export declare const enum SourceType {
  Script = 'Script',
  Module = 'Module',
  Jsx = 'Jsx',
  Tsx = 'Tsx',
  Typescript = 'Typescript'
}

export interface TransformOptions {
  sourceType?: SourceType
  jsx?: boolean
  jsxRuntime?: JsxRuntime
  jsxPragma?: string
  jsxPragmaFrag?: string
  jsxImportSource?: string
  typescript?: boolean
  sourcemap?: boolean
}

export interface TransformResult {
  code: string
  map?: string
  errors: Array<string>
  diagnostics: Array<Diagnostic>
}

export declare function transformSync(filename: string, sourceText: string, options?: TransformOptions | undefined | null): TransformResult
