/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FacetPack {
  constructor()
  parse(filename: string, sourceText: string, options?: ParseOptions | undefined | null): ParseResult
  transform(filename: string, sourceText: string, options?: TransformOptions | undefined | null): TransformResult
  resolve(directory: string, specifier: string, options?: ResolverOptions | undefined | null): ResolveResult
}

export declare const enum JsxRuntime {
  Automatic = 'Automatic',
  Classic = 'Classic'
}

export interface ParseOptions {
  sourceType?: SourceType
  preserveParens?: boolean
}

export interface ParseResult {
  program: string
  errors: Array<string>
  panicked: boolean
}

export declare function parseSync(filename: string, sourceText: string, options?: ParseOptions | undefined | null): ParseResult

export declare function resolveBatchSync(directory: string, specifiers: Array<string>, options?: ResolverOptions | undefined | null): Array<ResolveResult>

export interface ResolveResult {
  path?: string
  error?: string
}

export interface ResolverOptions {
  extensions?: Array<string>
  mainFields?: Array<string>
  conditionNames?: Array<string>
}

export declare function resolveSync(directory: string, specifier: string, options?: ResolverOptions | undefined | null): ResolveResult

export declare const enum SourceType {
  Script = 'Script',
  Module = 'Module',
  Jsx = 'Jsx',
  Tsx = 'Tsx',
  Typescript = 'Typescript'
}

export interface TransformOptions {
  sourceType?: SourceType
  jsx?: boolean
  jsxRuntime?: JsxRuntime
  jsxPragma?: string
  jsxPragmaFrag?: string
  jsxImportSource?: string
  typescript?: boolean
  sourcemap?: boolean
}

export interface TransformResult {
  code: string
  map?: string
  errors: Array<string>
}

export declare function transformSync(filename: string, sourceText: string, options?: TransformOptions | undefined | null): TransformResult
